#
# Macro file for the initialization phase of "TestEm1.cc"
#
# Sets some default verbose
# and initializes the graphic.
### /control/execute  gps3.mac

/control/verbose 2
/tracking/verbose 2
/run/verbose 2
/event/verbose 2

#PHYSICS
#/Physics/addPhysics QGSP_BIC_EMY
#/Physics/addPhysics QGSP_BERT
/run/initialize
/process/inactivate compt
/process/inactivate phot
/process/inactivate conv
/process/inactivate annihil

##  main beam
## 11 MeV lungo l'asse z positivo
#/gps/verbose 2
/gps/source/intensity 1.0
/gps/direction 0. 0. -1.
/gps/particle gamma
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 10. cm
/gps/pos/radius 0.02 mm 
#/gps/pos/rot1 0 0 1
#/gps/pos/rot2 1 1 0
## /gps/ang/type iso
#/gps/ang/type focused
#/gps/ang/focuspoint 0. 0. 0.
## spot size 15-30 um

## divergence 25-200 urad
#/gps/ang/sigma_r 0.0002 rad
/gps/ene/type Gauss
# ENERGY 16.45 MeV
/gps/ene/mono 31 MeV
/gps/ene/sigma 0.015
## /gps/polarization 0. 0. 1.


######################### V I S U A L I Z A T I O N ######################
/vis/open OGL 600x600-0+0
#/vis/open HepRepFile
#/vis/viewer/set/autoRefresh false
/vis/verbose c
/vis/drawVolume

/vis/geometry/set/visibility ChamberLogic 0 0
/vis/geometry/set/visibility ChamberLogic1 0 0
/vis/geometry/set/visibility ChamberLogic2 0 0

#/vis/geometry/set/visibility MagnesiumLayerLogic 0 0
#/vis/geometry/set/visibility CarbonLayerLogic 0 0

/testhadr/DrawTracks all
#/testhadr/event/drawTracks all
#/tracking/storeTrajectory 3
/vis/scene/add/trajectories rich smooth

#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/set 2 green
#/vis/modeling/trajectories/drawByCharge-0/set 1 blue
#/vis/modeling/trajectories/drawByCharge-0/set -1 red
#/vis/modeling/trajectories/drawByCharge-0/set 0 white
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/setDefault yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha red
/vis/modeling/trajectories/drawByParticleID-0/set gamma white
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set e- grey
/vis/modeling/trajectories/drawByParticleID-0/set e+ grey
/vis/modeling/trajectories/drawByParticleID-0/set neutron cyan


/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 5
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 5
/vis/modeling/trajectories/drawByParticleID-0/default/setTimeSliceInterval 0.1 ns

#Create a drawByAttribute model named drawByAttribute-0
#/vis/modeling/trajectories/create/drawByAttribute
#Configure drawByAttribute-0 model
#/vis/modeling/trajectories/drawByAttribute-0/verbose true
#Select attribute "CPN"
#/vis/modeling/trajectories/drawByAttribute-0/setAttribute CPN
#Configure single value data 
#/vis/modeling/trajectories/drawByAttribute-0/addValue pn_key  photonNuclear

# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true

/vis/verbose warnings
/vis/viewer/set/viewpointThetaPhi 70 130

#/vis/ogl/set/printMode pixmap
/vis/ogl/set/startTime 0.001 ns
/vis/ogl/set/endTime 5 ns
#shoot
#/vis/ogl/set/fade 1
/vis/ogl/set/displayHeadTime true
/control/alias timeRange 1
/control/loop movie.loop startTime -{timeRange} 40 0.1
/run/beamOn 1
#/vis/viewer/refresh


